version: '3.0'
services:
  expressjs:
    build:
      context: .
    ports:
    - 3000:3000
    networks:
      internship-network:
        ipv4_address: 173.20.128.2
    command: bash -c "npm start"
    volumes:
    - .:/app
    - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    networks:
      internship-network:
        ipv4_address: 173.20.128.1
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./storage/database:/data/db

networks:
  internship-network:
    ipam:
      config:
        - subnet: 173.20.0.0/16